# -*- coding: utf-8 -*-
"""nlp project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vraFJF-MaTblWEcGO0MSAzmorDJHpDFL

imp: already sqlite 3 is there so no need to import it again
"""

!pip install pandas
#!pip install sqlite3
!pip install nltk
!pip install tabulate
!pip install pandasql

"""pandas → handle CSV & tables

nltk → Natural Language Processing

matplotlib → charts,vizualization

tabulate → clean table display

sqlite3 → allows SQL queries

word_tokenize → split sentence into words

stopwords → remove useless words
"""

import sqlite3
print(sqlite3.sqlite_version)

import pandas as pd
import matplotlib.pyplot as plt
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from pandasql import sqldf
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
pysqldf = lambda q: sqldf(q, globals())

df = pd.read_csv("/content/ecommerce_dataset_10000.csv")
df.head()

conn = sqlite3.connect("analytics.db")
df.to_sql("sales", conn, index=False, if_exists="replace")
#Creates a SQLite database file
#Converts DataFrame → SQL table
#name = sales

pd.read_sql("SELECT * FROM sales LIMIT 5", conn) #similar to head

#nlp processing
def preprocess(text):
    tokens = word_tokenize(text.lower())
    stop_words = set(stopwords.words("english"))
    keywords = [w for w in tokens if w.isalnum() and w not in stop_words]
    #print("Keywords inside function:", keywords)
    return keywords
#1.Convert to lowercase(see actually what happens when u run the code if the sentence is mix of capital,small letters,or completely capital this condition converst all into 1 format whcih makes it to identify alleasily or else when u write in small and u given to identify in capital then they dont match as python conisders both as different words) ,2.Break into words(tokenization),3.Remove words like: show, by, the 4.Keep meaningful words)

def generate_sql(keywords):

    # 1️⃣ Total quantity by product
    if "total" in keywords and "quantity" in keywords and "product" in keywords:
        return """
        SELECT product_name, SUM(quantity) AS total_quantity
        FROM df
        GROUP BY product_name
        """

    # 2️⃣ Total sales / revenue
    elif "total" in keywords and ("sales" in keywords or "revenue" in keywords):
        return """
        SELECT SUM(quantity * unit_price) AS total_sales
        FROM df
        """

    # 3️⃣ Category wise quantity
    elif "category" in keywords and "quantity" in keywords:
        return """
        SELECT category, SUM(quantity) AS total_quantity
        FROM df
        GROUP BY category
        """

    # 4️⃣ Average rating by product ⭐ (NEW)
    elif "average" in keywords and "rating" in keywords:
        return """
        SELECT product_name, AVG(rating) AS avg_rating
        FROM df
        GROUP BY product_name
        """

    # 5️⃣ Country wise sales 🌍 (NEW)
    elif "country" in keywords and "sales" in keywords:
        return """
        SELECT country, SUM(quantity * unit_price) AS total_sales
        FROM df
        GROUP BY country
        """

    # 6️⃣ Payment method usage 💳 (NEW)
    elif "payment" in keywords:
        return """
        SELECT payment_method, COUNT(order_id) AS total_orders
        FROM df
        GROUP BY payment_method
        """

    # 7️⃣ Monthly sales trend 📅 (NEW)
    elif "monthly" in keywords and "sales" in keywords:
        return """
        SELECT substr(order_date,1,7) AS month,
               SUM(quantity * unit_price) AS total_sales
        FROM df
        GROUP BY month
        ORDER BY month
        """

    # 8️⃣ Show everything
    elif "all" in keywords or "show" in keywords:
        return "SELECT * FROM df LIMIT 20"

    else:
        return None

def ask_question():
    text = input("Ask your question: ")
    keywords = preprocess(text)
    sql_query = generate_sql(keywords)

    if sql_query is None:
        print("Sorry, I couldn't understand your query.")
        return

    result = pysqldf(sql_query)

    if result.empty:
        print("Query returned no results.")
        return

    display(result)

    # 📊 Automatic Visualization
    if len(result.columns) == 2:
        x, y = result.columns
        result.plot(kind="bar", x=x, y=y)
        plt.title(f"{y} by {x}")
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()

ask_question()

ask_question()

ask_question()

ask_question()

ask_question()

ask_question()

from pandasql import sqldf

query = """
SELECT product_name, SUM(quantity) AS total_quantity
FROM df
GROUP BY product_name
"""

result = sqldf(query, {"df": df})
print(result)

if not result.empty:
    result.plot(
        kind="bar",
        x="product_name",
        y="total_quantity",
        figsize=(10,5)
    )
    plt.title("Total Quantity Sold by Product")
    plt.show()

query = """
SELECT category, SUM(quantity * unit_price) AS total_sales
FROM df
GROUP BY category
"""
result = sqldf(query, {"df": df})

if not result.empty:
    result.plot(
        kind="pie",
        y="total_sales",
        labels=result["category"],
        autopct="%1.1f%%",
        legend=False,
        figsize=(6,6)
    )
    plt.title("Sales Distribution by Category")
    plt.ylabel("")
    plt.show()

query = """
SELECT substr(order_date,1,7) AS month,
       SUM(quantity * unit_price) AS total_sales
FROM df
GROUP BY month
ORDER BY month
"""
result = sqldf(query, {"df": df})

if not result.empty:
    result.plot(kind="line", x="month", y="total_sales", marker="o")#line chart
    plt.title("Monthly Sales Trend")
    plt.xticks(rotation=45)
    plt.show()

query = """
SELECT product_name, SUM(quantity * unit_price) AS sales
FROM df
GROUP BY product_name
ORDER BY sales DESC
LIMIT 5
"""
result = sqldf(query, {"df": df})

if not result.empty:
    result.plot(kind="bar", x="product_name", y="sales", figsize=(8,5))
    plt.title("Top 5 Products by Sales")
    plt.xticks(rotation=30)
    plt.show()

query = """
SELECT gender, SUM(quantity) AS total_quantity
FROM df
GROUP BY gender
"""
result = sqldf(query, {"df": df})

if not result.empty:
    result.plot(kind="bar", x="gender", y="total_quantity")
    plt.title("Purchases by Gender")
    plt.show()

query = """
SELECT product_name, AVG(rating) AS avg_rating
FROM df
GROUP BY product_name
"""
result = sqldf(query, {"df": df})

if not result.empty:
    result.plot(kind="bar", x="product_name", y="avg_rating", figsize=(9,5))
    plt.title("Average Product Ratings")
    plt.xticks(rotation=45)
    plt.show()

query = """
SELECT country, SUM(quantity * unit_price) AS total_sales
FROM df
GROUP BY country
ORDER BY total_sales DESC
"""
result = sqldf(query, {"df": df})

if not result.empty:
    result.plot(kind="barh", x="country", y="total_sales", figsize=(8,6))
    plt.title("Country-wise Sales")
    plt.show()

query = """
SELECT order_date, COUNT(order_id) AS total_orders
FROM df
GROUP BY order_date
ORDER BY order_date
"""
result = sqldf(query, {"df": df})

if not result.empty:
    plt.figure(figsize=(10,4))
    plt.plot(result["order_date"], result["total_orders"], marker='o') #Line Chart – Daily Orders Trend
    plt.title("Daily Orders Trend")
    plt.xticks(rotation=45)
    plt.show()

query = """
SELECT age_group FROM df
"""
result = sqldf(query, {"df": df})

if not result.empty:
    plt.hist(result["age_group"], bins=10)
    plt.title("Customer Age Group Distribution") #histogram Customer Age Group Distribution
    plt.xlabel("Age Group")
    plt.ylabel("Count")
    plt.show()

pivot = df.pivot_table(
    index="product_name",
    values="rating",
    aggfunc="mean"
)

plt.figure(figsize=(8,6))
plt.imshow(pivot, aspect='auto')
plt.colorbar(label="Average Rating")         #Heatmap – Product vs Rating (Advanced)
plt.title("Product Rating Heatmap")
plt.yticks(range(len(pivot.index)), pivot.index)
plt.show()

query = """
SELECT unit_price, quantity FROM df
"""
result = sqldf(query, {"df": df})

if not result.empty:
    plt.scatter(result["unit_price"], result["quantity"]) # Scatter Plot – Price vs Quantity
    plt.xlabel("Unit Price")
    plt.ylabel("Quantity Sold")
    plt.title("Price vs Quantity Relationship")
    plt.show()

plt.figure(figsize=(8,5))
df.boxplot(column="unit_price", by="category")
plt.title("Unit Price Distribution by Category")  # Box Plot – Price Distribution by Category
plt.suptitle("")
plt.show()

query = """
SELECT order_date, SUM(quantity * unit_price) AS sales
FROM df
GROUP BY order_date
ORDER BY order_date
"""
result = sqldf(query, {"df": df})

if not result.empty:
    plt.figure(figsize=(10,5))
    plt.fill_between(result["order_date"], result["sales"]) # Area Chart – Cumulative Sales Over Time
    plt.title("Sales Growth Over Time")
    plt.xticks(rotation=45)
    plt.show()

pivot = df.pivot_table(
    index="order_date",
    columns="category",
    values="quantity",
    aggfunc="sum"
)

pivot.plot.area(figsize=(10,5))
plt.title("Category-wise Quantity Trend Over Time") # Stacked Area Chart – Category-wise Sales Trend
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8,5))
plt.violinplot(df["rating"].dropna())
plt.title("Rating Distribution (Violin Plot)")
plt.ylabel("Rating") #Violin Plot (Distribution + Density)
plt.show()









